### ISSUE TITLE
canvas example breaks on resize

### ISSUE THREAD

**Issue by joe-getcouragenow** [ajstarks/giocanvas#3]
![Screenshot 2020-07-01 at 14 53 43](https://user-images.githubusercontent.com/59567750/86246117-c4465700-bbaa-11ea-8f86-a52aa604c0c7.png)

ONLY when you shrink it.

**Comment by ajstarks** [comment]
yes, the text elements move on resize, but the other elements do not.

**Comment by ajstarks** [comment]
fixed with revision  6e6994d
