### ISSUE TITLE
web demo test harness

### ISSUE THREAD

**Issue by joe-getcouragenow** [ajstarks/giocanvas#4]
I wonder if we should also have all the demos load in a web page too ?
Just a good test harness like the one you have now for desktop.

A simple index page that is just a page of links, that then call each demos index web page.
I think it can be scripted like your bc.sh approach...

**Comment by joe-getcouragenow** [comment]
I wrote it. Could you just drop them into the root of the repo ?

3 bash files to drop in root dir that matches your way of doing things.
[Archive.zip](https://github.com/ajstarks/giocanvas/files/4863353/Archive.zip)

wasm-build
- does all the needed build stuff

wasm.build-run
- runs it :)
- you will need to go get -u github.com/shurcooL/goexec

wasm-build-clean
- cleans out all build files

---

There is a problem when it runs the web server.
Each demo is in a subfolder of the root www, but WASM.exe is designed to ONLY run in the root path. 
Am messing around with this to see the fix...

**Comment by joe-getcouragenow** [comment]
> I wrote it. Could you just drop them into the root of the repo ?
> 
> 3 bash files to drop in root dir that matches your way of doing things.
> [Archive.zip](https://github.com/ajstarks/giocanvas/files/4863353/Archive.zip)
> 
> wasm-build
> 
> * does all the needed build stuff
> 
> wasm.build-run
> 
> * runs it :)
> * you will need to go get -u github.com/shurcooL/goexec
> 
> wasm-build-clean
> 
> * cleans out all build files
> 
> There is a problem when it runs the web server.
> Each demo is in a subfolder of the root www, but WASM.exe is designed to ONLY run in the root path.
> Am messing around with this to see the fix...
Mhh. Maybe its not running in the browser because of the fact that the go-mod is in root but we build it from the subfolder ?

**Comment by ajstarks** [comment]
Any more progress? I've attempted to re-create the wasm build, but I get nothing in the browser. (i suspect I'm doing something wrong).

**Comment by joe-getcouragenow** [comment]
I updated to the latest gio version and that helped load the WASM.
But it still fails.

I am honestly not sure whats wrong... I spent a few minutes brain storming but did not have time to keep going on it.
