### ISSUE TITLE
Failing to compile with latest gioui version - nov 25

### ISSUE THREAD

**Issue by hlima** [ajstarks/giocanvas#7]

**Comment by ajstarks** [comment]
yes, I plan to work on that soon.

**Comment by ajstarks** [comment]
Progress: now builds with the latest gioui, but images are broken.

**Comment by ajstarks** [comment]
Images fixed.

**Comment by hlima** [comment]
working great again.
Thanks

**Comment by hlima** [comment]
unfortunately image is not behaving properly ... The positioning does not seem to be correct nor the size..

**Comment by ajstarks** [comment]
@hlima can you show the code that is not working?

**Comment by hlima** [comment]
`canvas.CenterImage("earth.jpg", 50, 50, int(canvas.Width*0.06), 
                                                                        int(canvas.Height*0.09), 100)`
The code I am using is similar to the above. This should draw the image in the canvas center and have it proportionally resized. It is slightly off center and the resize does not seem to work.

**Comment by ajstarks** [comment]
I see, suggestion:  use the natural width, and height, and resize via the scale.

**Comment by hlima** [comment]
using scale seems to solve the resizing. thanks.
Position is still not working. seems to be better when the canvas size is increased. may be it is a rounding error?

**Comment by ajstarks** [comment]
See: https://github.com/ajstarks/giocanvas/tree/master/images
![images](https://user-images.githubusercontent.com/169692/101499475-519c8d00-393b-11eb-8fef-0c760a56d8b0.png)
